_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/home/ps/ltc/detectron2/experiments/monuseg18_lowres_small/model_final.pth"
  # WEIGHTS: "/home/ps/ltc/detectron2/experiments/monuseg18_lowres/model_final.pth"
  # WEIGHTS: "/home/ps/ltc/detectron2/experiments/monuseg18_lowres_6anchor/model_final.pth"
  # WEIGHTS: "/home/ps/ltc/detectron2/experiments/monuseg18_lowres_7anchor/model_final.pth"
  PIXEL_STD: [47.49, 41.63, 51.28]
  MASK_ON: False
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  ROI_HEADS:
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.05
    NMS_THRESH_TEST: 0.5
  ROI_BOX_HEAD:
    NUM_FC: 2
    NUM_CONV: 0
  ANCHOR_GENERATOR:
    SIZES: [[16], [24], [32], [48]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]

    # SIZES: [[16], [24], [32]]  # One size for each in feature map
    # ASPECT_RATIOS: [[0.5, 0.66, 1.0, 1.5, 2.0]]
    
    # SIZES: [[12], [16], [24]]  # One size for each in feature map
    # ASPECT_RATIOS: [[0.5,0.61,0.79,1.3,1.63,2.0]]

    # SIZES: [[12], [16], [24]]  # One size for each in feature map
    # ASPECT_RATIOS: [[0.5, 0.66, 0.83, 1.0, 1.2, 1.5, 2.0]]
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    # IN_FEATURES: ["p2", "p3", "p4"]
    # IN_FEATURES: ["p2", "p3", "p4"]
    # IN_FEATURES: ["p2", "p3", "p4"]

INPUT:
  MIN_SIZE_TEST: 0

DATASETS:
  TEST: ('voc_2007_wsi',)
  POST_PROCESS:
    FINAL_NMS_THR: 0.1
    AXIS_THR: 5.0
    AREA_THR: 50.0
  CLUSTER_PARAMETER:
    PRIOR: "/media/ps/passport1/ltc/monuseg18/MoNuSeg 2018 WSI patches 1000/patches/" #######################
    SCALE: 2.0

TEST:
  DETECTIONS_PER_IMAGE: 2000

SAVE_DIR: "/media/ps/passport1/ltc/monuseg18/experiments_output/monuseg18_wsi_lowres_small/" #######################
  
