_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  PIXEL_STD: [47.49, 41.63, 51.28]
  MASK_ON: False
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  ROI_HEADS:
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.05
    NMS_THRESH_TEST: 0.5
  ROI_BOX_HEAD:
    NUM_FC: 2
    NUM_CONV: 0
  ANCHOR_GENERATOR:
    SIZES: [[12], [16], [24]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5,0.61,0.79,1.3,1.63,2.0]]
  RPN:
    IN_FEATURES: ["p2", "p3", "p4"]
INPUT:
  MIN_SIZE_TRAIN: (500,)
  MAX_SIZE_TRAIN: 500
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.9, 0.9]
  
DATASETS:
  TRAIN: ('voc_2007_trainval',)
  TEST: ('voc_2007_val',)

SOLVER:
  GAMMA: 0.96
  STEPS: (300,400)  # 学习率衰减点调整到原来的 2 倍
  MAX_ITER: 500  # 翻倍，保证总训练量一致
  WARMUP_ITERS: 200  # 可适当增加，避免过大的初始波动
  IMS_PER_BATCH: 2  # 单 GPU 训练，batch size 减半
  BASE_LR: 0.003  # 学习率减半，适配 batch size
  CHECKPOINT_PERIOD: 100
  
TEST:
  EXPECTED_RESULTS: [['bbox', 'AP', 0, 100]]
  EVAL_PERIOD: 50
  DETECTIONS_PER_IMAGE: 2000
  
OUTPUT_DIR: "/home/ps/ltc/detectron2/experiments/monuseg18_lowres_6anchor_new/" #######################
  
